### ISSUE TITLE
Provide docker files or rpm files to support installation for AWS CloudHSM and other HSM solutions

### ISSUE THREAD

**Issue by vveselov** [aws-samples/aws-kms-xks-proxy#45]
### Security issue notifications

No potential security issues.

### Problem:

The current Docker file supports only SoftHSM2 installation, when the sample settings files are provided for different platforms.
The RPM script is for CentOS.

### Solution:

It will simplify the effort to use aws-kms-xks-proxy if Dockerfiles and rpm scripts were provided for other HSM, like AWS CloudHSM.
For example, OS -Amazon Linux 2023, HSM - AWS Cloud HSM

### Out of scope:

Is there anything the solution will intentionally NOT address?

[//]: #  (NOTE: If you believe this might be a security issue, please email aws-security@amazon.com instead of creating a GitHub issue. For more details, see the AWS Vulnerability Reporting Guide: https://aws.amazon.com/security/vulnerability-reporting/ )

**Comment by hansonchar** [comment]
Hi @vveselov, contributions are welcome.  We will be happy to review pull requests to support more environments and/or platforms.
